# .streamlit/secrets.toml

# OpenWeatherMap API Key
OPENWEATHERMAP_API_KEY = '3243453cd5b20c3a5f22014c074c1f74'

# NewsAPI.org API Key
NEWS_API_KEY = '3aedd8992d7642abac350a728dc4c7c4'

# Google Gemini API Key
GEMINI_API_KEY = 'AIzaSyA-3B6LWqgb41cPvRlt7UbS4WNaNGuZyt4'

# Gmail Credentials (for sending emails)
# IMPORTANT: Use an App Password if you have 2-Factor Auth enabled on Gmail
GMAIL_USER = 'roygitongarodney@gmail.com'
GMAIL_APP_PASSWORD = 'kzvz yhuv bswl ozoh' # Or your regular password if 2FA is off (not recommended)